# Set up daily and hourly local security scanning
#
# Copyright (c) 2016-2020, Yan Li <yanli@tuneup.ai>,
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of yan-common nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---
- name: install packages for RedHat
  yum: name=clamav,clamav-update,logrotate
       state=latest
  when: ansible_os_family == "RedHat"

- name: install packages for Debian
  apt: name=clamav
  when: ansible_os_family == "Debian"

- name: enable freshclam for RedHat
  lineinfile:
    dest:   /etc/freshclam.conf
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
  with_items:
    - { regexp: 'Example$', line: '# Example' }
    - { regexp: 'DatabaseMirror db\...\.clamav\.net', line: 'DatabaseMirror db.us.clamav.net' }
    - { regexp: 'Checks', line: 'Checks 1' }
  when: ansible_os_family == "RedHat"

- name: enable freshclam in sysconfig
  lineinfile:
    dest:   /etc/sysconfig/freshclam
    regexp: "^FRESHCLAM_DELAY=disabled-warn.*"
    state:  absent
  when: ansible_os_family == "RedHat"

- name: enable freshclam for Debian
  debconf:
    name: clamav-freshclam
    question: "{{ item.question }}"
    vtype: "{{ item.vtype }}"
    value: "{{ item.value }}"
  with_items:
    - { question: 'clamav-freshclam/Bytecode', vtype: 'boolean', value: 'true' }
    - { question: 'clamav-freshclam/update_interval', vtype: 'string', value: '1' }
    - { question: 'clamav-freshclam/LogRotate', vtype: 'boolean', value: 'true' }
  when: ansible_os_family == "Debian"

- name: clamav log directory
  file: path=/var/log/clamav
        state=directory

- name: enable daily clam scanning
  template:
    src: full_clamscan.j2
    dest: /etc/cron.weekly/full_clamscan
    owner: root
    group: root
    mode: '0755'
    backup: yes
